# Generated by Django 4.0.4 on 2022-04-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
