# Generated by Django 4.0.4 on 2022-04-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_input_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='link',
        ),
    ]
