# Generated by Django 4.0.4 on 2022-04-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_remove_input_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=500)),
                ('data', models.TextField()),
                ('words', models.IntegerField()),
                ('filler_words', models.IntegerField()),
                ('grammatical_errors', models.IntegerField()),
                ('pauses', models.IntegerField()),
                ('repeated_words', models.IntegerField()),
                ('variation', models.IntegerField()),
            ],
        ),
    ]
