# Generated by Django 4.0.4 on 2022-04-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='data',
        ),
    ]
